site_name: ИТ материалы
site_url: https://infdev.github.io/UsefulDevMaterials/
site_author: Александр Шляхто
site_description: >-
  ИТ-материалы как шпаргалка для разработчика и пользователей ПК

# Repository
repo_name: InfDev/UsefulDevMaterials
repo_url: https://github.com/InfDev/UsefulDevMaterials
edit_uri: edit/main/docs/

# Copyright
copyright: Авторские права &copy; 2019-2021 Александр Шляхто

# Configuration
theme:
  name: material
  language: ru

  palette:
    #    scheme: dracula
    #    primary: deep purple
    #    accent: deep purple

    - scheme: default
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/weather-sunny
        name: Перейти в темный режим
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Перейти в светлый режим
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.annotate
    - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

# Customization
extra:
  #  analytics:
  #    provider: google
  #    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/InfDev

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      linenums_style: table
  #  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: InfDev
      repo: UsefulDevMaterials
  - pymdownx.mark
  - pymdownx.smartsymbols

#extra_css:
#  - assets/css/extra.css
#extra_javascript:
#  - assets/js/extra.js

# Navigation
nav:
  - Начало:
      - index.md
      - development-platforms.md
      - trends-soft-development.md
      - trends-programming-languages.md
      - how-to-find-work.md
  - Навыки:
      - skills/index.md
      - skills/time-management.md
      - skills/ukrainian-language.md
      - skills/english-language.md
      - skills//business-correspondence.md
      - "Работа с ПК":
          - skills/for-pc-users/index.md
          - skills/for-pc-users/about-pc.md
          - skills/for-pc-users/pc-software.md
          - skills/for-pc-users/work-with-documents-on-pc.md
          - skills/for-pc-users/common-apps.md
          - skills/for-pc-users/online-services.md
      - "Мир и личность":
          - skills/peace-and-personality/chasing-progress.md
          - skills/peace-and-personality/professionalism.md
          - skills/peace-and-personality/hierarchy-of-needs.md
          - skills/peace-and-personality/procrastination.md
  - Документирование:
      - documenting/index.md
      - documenting/gendoc-mkdocs.md
      - documenting/gendoc-docfx.md
      - documenting/gendoc-sphinx.md
      - documenting/markdown.md
      - documenting/markdown-commonmark.md
      - documenting/markdown-github.md
      - documenting/markdown-here.md
      - documenting/html-special-characters.md
  - Стандарты:
      - standards/index.md
      - standards/what-standards-to-follow.md
      - standards/maintenance-standards.md
      - standards/naming-conventions.md
      - standards/openapi.md
      - standards/license-types.md
  - Системы:
      - system-tools/windows-terminal.md
      - system-tools/powershell-core.md
      - system-tools/cmd-windows.md
      - system-tools/wsl.md
      - system-tools/linux.md
      - system-tools/git-and-github.md
      - system-tools/docker.md
  - Проектирование:
      - designing/programming-paradigms.md
      - designing/oop.md
      - designing/oop.solid.md
      - designing/functional-programming.md
      - designing/design-patterns.md
      - designing/refactoring.md
      - designing/resources.md
  - .NET:
      - dotnet/index.md
      - dotnet/development-tools.md
      - dotnet/csharp.md
      - dotnet/csharp-practices-2021.md
      - dotnet/examples-fs.md
  - Python:
      - python/index.md
  - Разное:
      - general/cron-expressions.md
      - general/e-commerce.md
