site_name: ИТ материалы
site_url: https://example.com/

# Repository
repo_name: InfDev/UsefulDevMaterials
repo_url: https://github.com/InfDev/UsefulDevMaterials
edit_uri: edit/main/docs/

# Copyright
copyright: Авторские права &copy; 2021 Александр Шляхто

# Configuration
theme:
  name: material
  language: ru
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Перейти в темный режим
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Перейти в светлый режим
  features:
    - navigation.tabs
    - navigation.top

# Навигация
nav:
  - Дом: index.md
  - Общие:
      - general/documenting/index.md
      - Стандарты:
          - general/standards/index.md
  - .NET: .net/index.md
  - Python: python/index.md
  - Системные: system-tools/index.md
  - Навыки:
      - general-skills/index.md
