site_name: ИТ материалы
site_url: https://example.com/

# Repository
repo_name: InfDev/UsefulDevMaterials
repo_url: https://github.com/InfDev/UsefulDevMaterials
edit_uri: edit/main/docs/

# Copyright
copyright: Авторские права &copy; 2019-2021 Александр Шляхто

# Configuration
theme:
  name: material
  language: ru
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Перейти в темный режим
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Перейти в светлый режим
  features:
    - navigation.tabs
    - navigation.top

# Навигация
nav:
  - Дом: index.md
  - Общие:
      - Документирование:
          - general/documenting/index.md
          - general/documenting/gendoc-mkdocs.md
          - general/documenting/gendoc-docfx.md
          - general/documenting/gendoc-sphinx.md
          - general/documenting/markdown.md
          - general/documenting/markdown-commonmark.md
          - general/documenting/markdown-github.md
          - general/documenting/markdown-here.md
          - general/documenting/html-special-characters.md
      - Стандарты:
          - general/standards/index.md
          - general/standards/what-standards-to-follow.md
          - general/standards/maintenance-standards.md
          - general/standards/naming-conventions.md
          - general/standards/openapi.md
      - general/types-of-licenses.md
      - general/programming-paradigms.md
      - "Объектно-ориентированное программирование":
          - general/oop/index.md
          - general/oop/solid.md
      - general/design-patterns.md
      - general/refactoring.md
      - general/automation-with-docker.md
      - general/resources.md
      - general/cron-expressions.md
      - general/e-commerce.md
  - .NET:
      - dotnet/index.md
      - dotnet/development-tools.md
      - dotnet/csharp.md
      - dotnet/csharp-practices-2021.md
  - Python: python/index.md
  - Системные: system-tools/index.md
  - Навыки:
      - general-skills/index.md
      - general-skills/ukrainian-language.md
      - general-skills//business-correspondence.md
      - general-skills/time-management.md
      - general-skills/procrastination.md
